backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projeler"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Açıklama", name: "description", widget: "text" }
      - { label: "Görsel", name: "image", widget: "image" }
      - { label: "Müşteri Yorumu", name: "testimonial", widget: "text", required: false }
